# This is a basic workflow to help you get started with Actions
name: Auto pull main

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: pull
    runs-on: ubuntu-latest
    # pasos
    steps:
    - name: ejecutar pull en servidor mediante ssh
    #  uses: Daugus/igkluba@main
      with:
        host: ${{ secrets.IP }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd ${{ secrets.REPO_PATH }}
          git pull
